### ISSUE TITLE
USER STORY: Tasks

### ISSUE THREAD

**Issue by Lee-moran** [Lee-moran/love-running#2]
In order to provide anonymous feedback as a user, I can choose to hide my identity in the poll response 

# Acceptance Criteria:

- A. The option should be provided as a checkbox
- B. The checkbox should be "checked" by default
- C.  The option should appear next to the submission button 
- D. After submitting the default submission confirmation should be adjusted to include the user name 

# Task
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update the unit text scripts
- [ ] Test the functionality
